"""PYGAME EXTRA floating parameters
This script provides floating parameters which can be used to FLOAT contexts"""

FLOAT_LEFT = (-1, 0)
FLOAT_START = FLOAT_LEFT

FLOAT_RIGHT = (1, 0)
FLOAT_END = FLOAT_RIGHT

FLOAT_UP = (0, -1)
FLOAT_TOP = FLOAT_UP

FLOAT_DOWN = (0, 1)
FLOAT_BOTTOM = FLOAT_DOWN

FLOAT_CENTER = (0, 0)
FLOAT_MIDDLE = FLOAT_CENTER

FLOAT_UPPER_LEFT = (-1, -1)
FLOAT_UPPER_START = FLOAT_UPPER_LEFT
FLOAT_TOP_LEFT = FLOAT_UPPER_LEFT
FLOAT_TOP_START = FLOAT_UPPER_LEFT

FLOAT_UPPER_RIGHT = (1, -1)
FLOAT_UPPER_END = FLOAT_UPPER_RIGHT
FLOAT_TOP_RIGHT = FLOAT_UPPER_RIGHT
FLOAT_TOP_END = FLOAT_UPPER_RIGHT

FLOAT_BOTTOM_LEFT = (-1, 1)
FLOAT_BOTTOM_START = FLOAT_BOTTOM_LEFT
FLOAT_DOWN_LEFT = FLOAT_BOTTOM_LEFT
FLOAT_DOWN_START = FLOAT_BOTTOM_LEFT

FLOAT_BOTTOM_RIGHT = (1, 1)
FLOAT_BOTTOM_END = FLOAT_BOTTOM_RIGHT
FLOAT_DOWN_RIGHT = FLOAT_BOTTOM_RIGHT
FLOAT_DOWN_END = FLOAT_BOTTOM_RIGHT
