"""PYGAME EXTRA floating parameters
This script provides floating parameters which can be used to FLOAT contexts"""

FLOAT_LEFT = (-1, 0)
FLOAT_START = FLOAT_LEFT

FLOAT_RIGHT = (1, 0)
FLOAT_END = FLOAT_RIGHT

FLOAT_UP = (0, -1)
FLOAT_TOP = FLOAT_UP

FLOAT_DOWN = (0, 1)
FLOAT_BOTTOM = FLOAT_DOWN

FLOAT_CENTER = (0, 0)
FLOAT_MIDDLE = FLOAT_CENTER

FLOAT_UPPERLEFT = (-1, -1)
FLOAT_UPPERSTART = FLOAT_UPPERLEFT
FLOAT_TOPLEFT = FLOAT_UPPERLEFT
FLOAT_TOPSTART = FLOAT_UPPERLEFT

FLOAT_UPPERRIGHT = (1, -1)
FLOAT_UPPEREND = FLOAT_UPPERRIGHT
FLOAT_TOPRIGHT = FLOAT_UPPERRIGHT
FLOAT_TOPEND = FLOAT_UPPERRIGHT

FLOAT_BOTTOMLEFT = (-1, 1)
FLOAT_BOTTOMSTART = FLOAT_BOTTOMLEFT
FLOAT_DOWNLEFT = FLOAT_BOTTOMLEFT
FLOAT_DOWNSTART = FLOAT_BOTTOMLEFT

FLOAT_BOTTOMRIGHT = (1, 1)
FLOAT_BOTTOMEND = FLOAT_BOTTOMRIGHT
FLOAT_DOWNRIGHT = FLOAT_BOTTOMRIGHT
FLOAT_DOWNEND = FLOAT_BOTTOMRIGHT
